# Generated by Django 4.2 on 2026-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("google", "Google Ads"),
                            ("facebook", "Facebook Ads"),
                            ("twitter", "Twitter Ads"),
                            ("linkedin", "LinkedIn Ads"),
                            ("tiktok", "TikTok Ads"),
                            ("email", "Email"),
                            ("organic", "Organic"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "cost_per_click",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
