# Generated by Django 4.2 on 2026-06-17 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("first_touch", "First Touch"),
                            ("last_touch", "Last Touch"),
                            ("linear", "Linear"),
                        ],
                        max_length=50,
                    ),
                ),
                ("credit", models.DecimalField(decimal_places=4, max_digits=14)),
                ("calculated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribution_results",
                        to="channels.adchannel",
                    ),
                ),
            ],
            options={
                "ordering": ["-calculated_at", "-credit"],
            },
        ),
    ]
